services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        restart: 'always'
        ports:
            - "5004:5004"
            - "1883:1883"
        environment:
            - API_URL=${API_URL}
            - MQTT_USERNAME=${MQTT_USERNAME:-cloudtak-dji}
            - MQTT_PASSWORD=${MQTT_PASSWORD:-changeme}
